/*
 * PaintPanel.java
 *
 * Created on 7 April 2007, 14:45
 */

package usyd.comp5425.ui;

/**
 *
 * @author  Yuezhong Zhang
 */
public class PaintPanel extends javax.swing.JPanel {
    
    /** Creates new form PaintPanel */
    public PaintPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lineBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton1);

        jButton2.setText("Color");
        jToolBar1.add(jButton2);

        lineBtn.setText("Line");
        jToolBar1.add(lineBtn);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton lineBtn;
    // End of variables declaration//GEN-END:variables
    
}
